net:
  _target_: model.pointbert.pointbert.PointBERT
  trans_dim: 384
  depth: 12
  drop_path_rate: 0.1
  cls_dim: 40
  num_heads: 6
  group_size: 16   # 32
  num_group: 128   # 512
  encoder_dims: 256
  add_RGB: True

path: weights/pointbert_pointllm.pth
freeze: True
